### ISSUE TITLE
可执行文件区别及建议

### ISSUE THREAD

**Issue by whyseu** [cdk-team/CDK#15]
（1）cdk releases里面可执行文件后缀thin，upx，thin_upx都是什么意思？
（2）建议加入免杀

**Comment by neargle** [comment]
免杀能力不应该放入开源项目里哈，开源代码里应该是纯粹的和容器相关的feature。
不同版本的Release近期我们会加入一个wiki来描述他，主要是大小和功能的区别。

**Comment by whyseu** [comment]
OK
