### ISSUE TITLE
能否将debugfs读取设备文件，根据回显向设备文件写入payload这个过程自动化？

### ISSUE THREAD

**Issue by yangusrname** [cdk-team/CDK#33]
这个方法可行吗？根据debugfs里stat读取文件信息，根据这个回显里的信息，将payload写入一些文件当中。
还有很多利用方式，来使内核调用这种替换的文件，比如说利用内核转储之类的

我只是个菜鸡，想到这个地方，麻烦大佬们指正

**Comment by neargle** [comment]
有可能，不过我感觉用golang比较难实现

**Comment by neargle** [comment]
或者实现起来可能会很重

**Comment by Xyntax** [comment]
`cdk auto-escape` 这个功能的设计初衷是把多个exp/系统操作编排成一个自动化的利用链辅助测试，有点类似SOAR的playbook，后续没有继续跟进的考虑是太重了，应该另起一个项目。
