### ISSUE TITLE
最新版本执行“cdk ***”任意命令都会变为执行"cdk evaluate"

### ISSUE THREAD

**Issue by lqqqc** [cdk-team/CDK#37]
执行`run`命令时发现会打印执行`evaluate`的结果：
![3](https://user-images.githubusercontent.com/48820715/155514295-1505055a-2af0-42f0-bd85-8b06a09d5d7c.png)

甚至任意命令都是如此：
![2](https://user-images.githubusercontent.com/48820715/155514850-4e4f3144-c622-471b-9b98-a314aa923d7c.png)

经测试，`parse.go`中的变量`fok`值总为`true`（原因未找到）
![1](https://user-images.githubusercontent.com/48820715/155515118-4f1b6965-0d93-416b-b8ca-29ec162e8c50.png)

改成之前的`if Args["evaluate"].(bool){}`就没问题。

**Comment by neargle** [comment]
这个是开发版特性，确实判断有问题，幸好还没发布新版本打包，我的锅，周末改。

**Comment by neargle** [comment]
fix
