### ISSUE TITLE
shim-pwn模块会报错，panic: protobuf tag not enough fields in Status.state: 

### ISSUE THREAD

**Issue by ernongxizhu** [cdk-team/CDK#38]
![image](https://user-images.githubusercontent.com/73651912/156345818-328f95bd-5191-4c9b-a0f3-3137b61baef2.png)
可能是protobuf的版本有问题？

**Comment by kmahyyg** [comment]
might related to PR #31

**Comment by neargle** [comment]
这里的cdk的是哪一个版本？

**Comment by neargle** [comment]
> might related to PR #31

fixed~
