### ISSUE TITLE
k8s-shadow-apiserver 返回包判断有问题

### ISSUE THREAD

**Issue by idlefire** [cdk-team/CDK#71]
## 请详细描述你遇到的问题 (Please describe the issue in detail)
使用cdk部署影子api server时，代码端判断selfLink，但是podlist里面没有该字段
k8s版本1.20.6
> Note: 提交issue前，请检查你所使用的CDK是否是最新版，有些BUG我们新版本已经修复啦。  
> Before submitting an issue, please check whether the CDK you are using is the latest version, otherwise there may be some bugs that have been fixed in latest version.

2、请贴出完整错误信息，可以是命令行输出、软件报错信息、截图等。(Please post the full error message, which can be command line output, software error message, screenshots, etc.)
```
./cdk run k8s-shadow-apiserver default
```
![image](https://user-images.githubusercontent.com/18007341/205416939-4f7267a0-60b5-4dc1-9d03-fda9a6c2a947.png)
![image](https://user-images.githubusercontent.com/18007341/205416982-1dffff6b-e074-4d18-a24c-97e81e39e4e8.png)
**注意，请贴出完整错误信息，不要只粘贴错误的最后一行！Attention, please post the full error message, don't paste the last line of the error only!**

**Comment by neargle** [comment]
好的，我更新一下测试环境的版本检查看看，感谢反馈～
