### ISSUE TITLE
关于cdk中 影子apiserver模块的疑问

### ISSUE THREAD

**Issue by QuanYex** [cdk-team/CDK#77]
在v1.1.1版本之前 因为还有--insecure-port=9443 ，因为k8s弃用之后 cdk也注释掉了，现在的话单靠
--anonymous-auth=true
--authorization-mode=AlwaysAllow
这两个参数 没有办法实现对安全端口的匿名访问，这个利用是不是还得建立在匿名用户高权的情况下？

谢谢！

**Comment by neargle** [comment]
对的 新的版本不允许开放 apiserver 的 anonymous-auth，这里后续的利用应该新建一个 apiserver 副本的同时，提供一个 cluster-admin 的账号权限以供利用，后续会找时间优化。

**Comment by QuanYex** [comment]
嗯嗯，谢谢解答！！如果sa的权限能创建影子api，那确实可以试试直接绑定角色，说不定权限没分那么细- . -。感谢~
