### ISSUE TITLE
wiki 无法下载

### ISSUE THREAD

**Issue by giantpetter** [cdk-team/CDK#95]
## 请详细描述你遇到的问题 (Please describe the issue in detail)

使用命令 `git clone https://github.com/cdk-team/CDK.wiki.git`
出现以下错误：
`Cloning into 'CDK.wiki'... `
`fatal: unable to access 'https://github.com/cdk-team/CDK.wiki.git/': Recv failure: Connection was reset`

**Comment by neargle** [comment]
hi，这个应该是你的网络问题哈，另外此类问题不应该直接伸手问哦
